apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: codeflare-stack
  namespace: opendatahub
spec:
  applications:
  # CodeFlare
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: codeflare-stack
    name: codeflare-stack
  # Ray.io
  - kustomizeConfig:
      repoRef:
        name: manifests-contrib
        path: ray/operator
    name: ray-operator
  repos:
    # ODH Core component manifests
  - name: manifests
    uri: https://github.com/opendatahub-io/distributed-workloads/tarball/main
    # ODH Contrib component manifests
  - name: manifests-contrib
    uri: https://github.com/opendatahub-io-contrib/odh-contrib-manifests/tarball/main
