apiVersion: datasciencecluster.opendatahub.io/v1
kind: DataScienceCluster
metadata:
  labels:
    app.kubernetes.io/created-by: opendatahub-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/part-of: opendatahub-operator
  name: example-dsc
spec:
  components:
    codeflare:
      enabled: true
    dashboard:
      enabled: true
    datasciencepipelines:
      enabled: false
    kserve:
      enabled: false
    modelmeshserving:
      enabled: false
    ray:
      enabled: true
    workbenches:
      enabled: true
