---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: llm-
  labels:
    kueue.x-k8s.io/priority-class: business-impacting
    kueue.x-k8s.io/queue-name: llm-queue
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["300s"]
        resources:
          requests:
            cpu: 50m
            memory: "50Mi"
      restartPolicy: Never



