apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: stable-diffusion
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: stable-diffusion
  namespace: distributed
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: pytorch
        version: '1'
      name: ''
      resources:
        limits:
          nvidia.com/gpu: '1'
        requests:     
          nvidia.com/gpu: '1'
      runtime: stable-diffusion
      storage:
        key: aws-connection-minio
        path: models
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists