kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: distributed
subjects:
  - kind: ServiceAccount
    name: stable-diffusion
    namespace: distributed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
