kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mcad-controller-ray-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: mcad-controller-mcad
    namespace: $(namespace)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcad-controller-ray-clusterrole
