resources:
- ray_rayjob_editor_role.yaml
- ray_rayjob_viewer_role.yaml
- ray_rayservice_editor_role.yaml
- ray_rayservice_viewer_role.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- service_account.yaml

commonLabels:
  app.kubernetes.io/name: kuberay
  app.kubernetes.io/component: kuberay-operator
