apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nfd
  namespace: openshift-nfd
---  
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
  labels:
    operators.coreos.com/nfd.openshift-nfd: ''
  namespace: openshift-nfd
spec:
  channel: stable
  name: nfd
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
