apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: team1
spec:
  cohort: "organization"
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: Never
    reclaimWithinCohort: Any
    withinClusterQueue: LowerOrNewerEqualPriority
  queueingStrategy: BestEffortFIFO
  resourceGroups:
    - coveredResources:
        - cpu
        - memory
        - nvidia.com/gpu
      flavors:
        - name: nvidia-h100-80gb
          resources:
            - name: cpu
              nominalQuota: '16'
            - name: memory
              nominalQuota: 256Gi
            - name: nvidia.com/gpu
              nominalQuota: '2'
        - name: nvidia-a100-80gb
          resources:
            - name: cpu
              nominalQuota: '64'
            - name: memory
              nominalQuota: 1024Gi
            - name: nvidia.com/gpu
              nominalQuota: '8'
  stopPolicy: None
