name: Go unit tests
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**go.mod'
      - '**go.sum'
  pull_request:
    paths:
      - '**.go'
      - '**go.mod'
      - '**go.sum'
jobs:
  unit-test:
    name: Go unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './go.mod'
    - name: Unit tests
      run: go test ./tests/common/support/...
